site_name: Semgrep Docs
site_url: https://semgrep.dev/docs/
nav:
  - Semgrep:
      - Home: index.md
      - getting-started.md
      - Writing rules:
          - writing-rules/overview.md
          - Syntax:
              - writing-rules/pattern-syntax.md
              - writing-rules/pattern-logic.md
          - Examples:
              - writing-rules/pattern-examples.md
              - writing-rules/rule-ideas.md
          - writing-rules/testing-rules.md
      - running-rules.md
      - managing-policy.md
      - integrations.md
      - experiments.md
  - "Security Cheat Sheets":
      - "Django XSS": "cheat-sheets/django-xss"
      - "Flask XSS": "cheat-sheets/flask-xss"
      - "Java/JSP XSS": "cheat-sheets/java-jsp-xss"
      - "Rails XSS": "cheat-sheets/rails-xss"
  - Stats:
      - Rules: rules.md
      - Supported languages: status.md
      - Trophy case: trophy-case.md
  - Help:
      - FAQ: faq.md
      - support.md
      - contributing.md
      - security.md
theme:
  name: readthedocs
  custom_dir: custom_theme/
  navigation_depth: 3
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - django
markdown_extensions:
  - admonition
  - toc
google_analytics:
  - UA-106134149-12
  - auto
extra_css: [extra.css]
